[workspace]
resolver = "3"
members = [
    "./bevy_hookup_core",
    "./bevy_hookup_macros",
    "./bevy_hookup_messenger_websocket",
    "./bevy_hookup_messenger_steamworks",
    "./examples/basic",
]
